//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooDataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id_client { get; set; }
        public int Id_prod { get; set; }
        public int Status { get; set; }
        public int id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Products Products { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
